drop table INCL_DETECTORS_FSM cascade constraints; 

/

CREATE TABLE INCL_DETECTORS_FSM
(  
   DS_CHAMBERS VARCHAR(100), 
   SOLAR_FLAG NUMBER(1) NOT NULL CHECK (SOLAR_FLAG IN (0,1)),
   GBT_FLAG NUMBER(1) NOT NULL CHECK (GBT_FLAG IN (0,1)),
   SAMPA_FLAG NUMBER(1) NOT NULL CHECK (SAMPA_FLAG IN (0,1))
);